version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  web:
    build: ./web-service
    depends_on:
      - mongodb
      - auth
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://admin:password@mongodb:27017/objaverse?authSource=admin
      - CLOUDINARY_CLOUD_NAME=your-cloud-name
      - CLOUDINARY_API_KEY=your-api-key
      - CLOUDINARY_API_SECRET=your-api-secret
      - JWT_SECRET=your-jwt-secret
    ports:
      - "3000:3000"
    volumes:
      - ./web-service:/app

  auth:
    build: ./auth-service
    depends_on:
      - mongodb
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://admin:password@mongodb:27017/objaverse-auth?authSource=admin
      - JWT_SECRET=your-jwt-secret
    ports:
      - "4000:4000"
    volumes:
      - ./auth-service:/app

volumes:
  mongodb_data: