apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: objaverse-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.159.89.216.26.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: objaverse-web-service
            port:
              number: 80
  - host: auth.159.89.216.26.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: objaverse-auth-service
            port:
              number: 4000
  - host: portal.159.89.216.26.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: objaverse-portal-service
            port:
              number: 8000