apiVersion: apps/v1
kind: Deployment
metadata:
  name: objaverse-portal
  labels:
    app: objaverse-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: objaverse-portal
  template:
    metadata:
      labels:
        app: objaverse-portal
    spec:
      imagePullSecrets:
      - name: registry-kedziora
      containers:
      - name: objaverse-portal
        image: registry.digitalocean.com/kedziora/objaverse-portal:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: API_URL
          value: "http://api.159.89.216.26.nip.io"
        - name: AUTH_URL
          value: "http://auth.159.89.216.26.nip.io"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: objaverse-secrets
              key: jwt-secret
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10