apiVersion: apps/v1
kind: Deployment
metadata:
  name: objaverse-web
  labels:
    app: objaverse-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: objaverse-web
  template:
    metadata:
      labels:
        app: objaverse-web
    spec:
      imagePullSecrets:
      - name: registry-kedziora
      containers:
      - name: objaverse-web
        image: registry.digitalocean.com/kedziora/objaverse-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: objaverse-secrets
              key: mongo-uri
        - name: AUTH_SERVICE_URL
          value: "http://auth.159.89.216.26.nip.io"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: objaverse-secrets
              key: jwt-secret
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: objaverse-secrets
              key: cloudinary-cloud-name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: objaverse-secrets
              key: cloudinary-api-key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: objaverse-secrets
              key: cloudinary-api-secret
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5